version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: helpdesk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/helpdesk?schema=public&sslmode=disable&pgbouncer=false"
    ports:
      - "3001:3001"
      - "5555:5555"
    depends_on:
      - db
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npx prisma db push && npx prisma studio --hostname 0.0.0.0 & ./start.sh"
    
volumes:
  postgres_data: